"""The spec catalog: sw's view of the authoritative API surface.

``spec_catalog.json`` is generated by ``scripts/build_catalog.py`` from
SignalWire's *compiled* OpenAPI and checked in, so sw knows every operation
without needing the specs at runtime. This module loads it once and exposes the
lookups the coverage gate, the registry, and the transport layer all use.

Routes are exact, not inferred. The previous generator regex-scraped the
TypeSpec sources and produced 41 wrong paths and 2 wrong methods, twelve of
which were repaired by hand here in a ``_ROUTE_FIXES`` table. Reading the
compiled OpenAPI removed the whole class of defect and the table with it.

Each operation also carries its request ``params``, which is what lets the field
audit check that a command offers what the API actually accepts.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_CATALOG_PATH = Path(__file__).with_name("spec_catalog.json")


@dataclass(frozen=True, slots=True)
class Param:
    """One request-body parameter, as the API documents it."""

    name: str
    type: str = ""
    required: bool = False
    enum: tuple[str, ...] = ()
    default: object = None
    description: str = ""


@dataclass(frozen=True, slots=True)
class Operation:
    """One API operation, as compiled from the specs."""

    api: str
    operation_id: str
    method: str
    path: str
    base_route: str = ""
    summary: str = ""
    params: tuple[Param, ...] = ()

    @property
    def key(self) -> str:
        """Stable identity. Operation ids collide across APIs (``create_message``
        is in both compat and message-api), so the API must qualify them."""
        return f"{self.api}:{self.operation_id}"

    @property
    def required_params(self) -> tuple[Param, ...]:
        return tuple(p for p in self.params if p.required)


@lru_cache(maxsize=1)
def _load() -> dict:
    return json.loads(_CATALOG_PATH.read_text())


@lru_cache(maxsize=1)
def operations() -> tuple[Operation, ...]:
    raw = _load()["operations"]
    return tuple(
        Operation(
            api=o["api"],
            operation_id=o["operation_id"],
            method=o["method"],
            path=o["path"],
            base_route=o.get("base_route", ""),
            summary=o.get("summary", ""),
            params=tuple(
                Param(
                    name=p["name"],
                    type=p.get("type", ""),
                    required=bool(p.get("required")),
                    enum=tuple(p.get("enum") or ()),
                    default=p.get("default"),
                    description=p.get("description", ""),
                )
                for p in o.get("params", [])
            ),
        )
        for o in raw
    )


@lru_cache(maxsize=1)
def by_key() -> dict[str, Operation]:
    """Every operation keyed by ``api:operation_id`` — the collision-free key."""
    return {op.key: op for op in operations()}


def get(operation_id: str, api: str | None = None) -> Operation | None:
    """Look up an operation.

    With ``api`` given, an exact ``api:operation_id`` lookup. Without it, returns
    the operation if the id is unambiguous across APIs, else None — so callers
    that pass a colliding id (``create_message``) are forced to qualify it.
    """
    if api is not None:
        return by_key().get(f"{api}:{operation_id}")
    matches = [op for op in operations() if op.operation_id == operation_id]
    return matches[0] if len(matches) == 1 else None


def candidates(operation_id: str) -> list[Operation]:
    """Every operation with this id, across all APIs.

    ``get`` deliberately returns None for an id that collides rather than
    guessing, which leaves the caller with nothing to say. Seventeen ids collide
    (``create_token`` is in three APIs), so `sw api` uses this to name the
    options instead of failing blankly.
    """
    return [op for op in operations() if op.operation_id == operation_id]


def by_api(api: str) -> list[Operation]:
    return [op for op in operations() if op.api == api]


def apis() -> dict[str, dict]:
    """API name -> {base_route, operations count}, from the catalog header."""
    return _load()["apis"]


def keys() -> set[str]:
    """Every ``api:operation_id`` key — the canonical operation identity set."""
    return set(by_key())


def total() -> int:
    return _load()["total"]
